version: "3"

services:
  api:
    build: .
    # prod docker-compose dosyasında build kısmı bulunmaz çünkü build işlemi değil image'ın alınması söz konusudur.
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
      # hotreload yapabilmek için volumes kısmında appi belirmetmemiz ve command kısmında uvicornu --reload ile başlatmamız gerekir.
      # "ro" tag'ı ReadOnly kısaltmasıdır ve container'ın sadece yapılan değişikleri uygulamasını
      # belirtir (container içerisinden app'te değişik yapılmayacağı ve containerın sadece okuma yapacağı bildirilir.)
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # - <port on localhost>:<port on container>
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=159632159
      - DATABASE_NAME=robomarkt_db
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=159632159
      - POSTGRES_DB=robomarkt_db
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
